# prevent re-build from smashing routes.  See https://www.youtube.com/watch?v=0M1y2EnkAAk
---
spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
# disable session persistence to help with reloading code
server:
  servlet:
    session:
      persistent: false